all: icon_atmo.nc icon_ocean.nc clouds.json land.json ESiWACE_HPDA_2021.pdf height.nc calculator.txt

%.*:
	wget 'https://swift.dkrz.de/v1/dkrz_8656c91ce0734327b6dc867fc5b6b068/ESiWACE2-Public/Paraview%20Sample%20Data/'$@




